/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvshowsIndexRouteImport } from './routes/tvshows/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as AnimeIndexRouteImport } from './routes/anime/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvshowsIndexRoute = TvshowsIndexRouteImport.update({
  id: '/tvshows/',
  path: '/tvshows/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime/': typeof AnimeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/tvshows/': typeof TvshowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/tvshows': typeof TvshowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime/': typeof AnimeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/tvshows/': typeof TvshowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime/' | '/movies/' | '/tvshows/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime' | '/movies' | '/tvshows'
  id: '__root__' | '/' | '/anime/' | '/movies/' | '/tvshows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  TvshowsIndexRoute: typeof TvshowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvshows/': {
      id: '/tvshows/'
      path: '/tvshows'
      fullPath: '/tvshows/'
      preLoaderRoute: typeof TvshowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  TvshowsIndexRoute: TvshowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
